<?php
//
// Competition System - Custom Parameters
//
// Generated: 2020-03-06 11:23:22
//
$dispfields["Bot"][0] = array("used"=>TRUE,"tag"=>"opstatus", "display"=>"Oper Status", "inputlen"=>4,"maxlen"=>4, "default_value"=>"");
$dispfields["Bot"][1] = array("used"=>TRUE,"tag"=>"drivetrain", "display"=>"Drivetrain", "inputlen"=>10,"maxlen"=>20, "default_value"=>"");
$dispfields["Bot"][2] = array("used"=>TRUE,"tag"=>"shooter", "display"=>"Shooter?", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][3] = array("used"=>TRUE,"tag"=>"highshooter", "display"=>"High Shooter?", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][4] = array("used"=>TRUE,"tag"=>"pickup", "display"=>"Pickup?", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][5] = array("used"=>TRUE,"tag"=>"scaling", "display"=>"Scaling Mech?", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][6] = array("used"=>TRUE,"tag"=>"specialmech", "display"=>"Special Mech?", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][7] = array("used"=>TRUE,"tag"=>"portcullis", "display"=>"Portcullis", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][8] = array("used"=>TRUE,"tag"=>"cheval", "display"=>"Cheval", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][9] = array("used"=>TRUE,"tag"=>"moat", "display"=>"Moat", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][10] = array("used"=>TRUE,"tag"=>"ramparts", "display"=>"Ramparts", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][11] = array("used"=>TRUE,"tag"=>"drawbridge", "display"=>"Drawbridge", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][12] = array("used"=>TRUE,"tag"=>"sallyPort", "display"=>"Sally Port", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][13] = array("used"=>TRUE,"tag"=>"rockwall", "display"=>"Rock Wall", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][14] = array("used"=>TRUE,"tag"=>"roughterrain", "display"=>"Rough Terrain", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][15] = array("used"=>TRUE,"tag"=>"lowbar", "display"=>"Low Bar", "inputlen"=>2,"maxlen"=>2, "default_value"=>"0");
$dispfields["Bot"][16] = array("used"=>TRUE,"tag"=>"speedrt", "display"=>"Speed Rating", "inputlen"=>1,"maxlen"=>1, "default_value"=>"5");
$dispfields["Bot"][17] = array("used"=>TRUE,"tag"=>"pickuprt", "display"=>"Pickup Rating", "inputlen"=>1,"maxlen"=>1, "default_value"=>"5");
$dispfields["Bot"][18] = array("used"=>TRUE,"tag"=>"lowrt", "display"=>"Low Shoot Rating", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][19] = array("used"=>TRUE,"tag"=>"highrt", "display"=>"High Shoot Rating", "inputlen"=>1,"maxlen"=>1, "default_value"=>"");
$dispfields["Bot"][20] = array("used"=>TRUE,"tag"=>"breachrt", "display"=>"Breach Rating", "inputlen"=>1,"maxlen"=>1, "default_value"=>"5");
$dispfields["Match"][0] = array("used"=>TRUE,"tag"=>"autoscorebot", "display"=>"Auto Score Bot", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][1] = array("used"=>TRUE,"tag"=>"autoscoretop", "display"=>"Auto Score Top", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][2] = array("used"=>TRUE,"tag"=>"AutoRockWall", "display"=>"AutoRock Wall", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][3] = array("used"=>TRUE,"tag"=>"AutoMoat", "display"=>"AutoMoat", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][4] = array("used"=>TRUE,"tag"=>"AutoDrawbridge", "display"=>"AutoDrawbridge", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][5] = array("used"=>TRUE,"tag"=>"AutoCheval", "display"=>"AutoCheval de frise", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][6] = array("used"=>TRUE,"tag"=>"AutoLowBar", "display"=>"AutoLow Bar", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][7] = array("used"=>TRUE,"tag"=>"startposition", "display"=>"startposition", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][8] = array("used"=>TRUE,"tag"=>"MissesHigh", "display"=>"Misses High", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][9] = array("used"=>TRUE,"tag"=>"MissesLow", "display"=>"Misses Low", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][10] = array("used"=>TRUE,"tag"=>"PercentAccuracy", "display"=>"Percent Accuracy", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][11] = array("used"=>TRUE,"tag"=>"driverrating", "display"=>"driverrating", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][12] = array("used"=>TRUE,"tag"=>"pickuprating", "display"=>"pickuprating", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][13] = array("used"=>TRUE,"tag"=>"BreacherRating", "display"=>"BreacherRating", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][14] = array("used"=>TRUE,"tag"=>"RockWallMatch", "display"=>"Rock Wall", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][15] = array("used"=>TRUE,"tag"=>"RockWallDiff", "display"=>"Rock Wall Difficult?", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][16] = array("used"=>TRUE,"tag"=>"MoatMatch", "display"=>"Moat", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][17] = array("used"=>TRUE,"tag"=>"MoatDiff", "display"=>"Moat Difficult?", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][18] = array("used"=>TRUE,"tag"=>"DrawbridgeMatch", "display"=>"Drawbridge", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][19] = array("used"=>TRUE,"tag"=>"DrawbridgeDiff", "display"=>"Drawbridge Diff?", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][20] = array("used"=>TRUE,"tag"=>"ChevalMatch", "display"=>"Cheval de frise", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][21] = array("used"=>TRUE,"tag"=>"ChevalDiff", "display"=>"Cheval Diff?", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][22] = array("used"=>TRUE,"tag"=>"LowBarMatch", "display"=>"Low Bar", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][23] = array("used"=>TRUE,"tag"=>"LowBarDiff", "display"=>"Low Bar Diff", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][24] = array("used"=>TRUE,"tag"=>"robottype", "display"=>"robottype", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][25] = array("used"=>TRUE,"tag"=>"PickupSpeed", "display"=>"Pickup Speed", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][26] = array("used"=>TRUE,"tag"=>"PickupStable", "display"=>"Pickup Stable", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][27] = array("used"=>TRUE,"tag"=>"telescorebot", "display"=>"telescorebot", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][28] = array("used"=>TRUE,"tag"=>"telescoretop", "display"=>"telescoretop", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][29] = array("used"=>TRUE,"tag"=>"TechFoul", "display"=>"TechFoul", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][30] = array("used"=>TRUE,"tag"=>"FinalPosit", "display"=>"FinalPosit", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][31] = array("used"=>TRUE,"tag"=>"redcard", "display"=>"redcard", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][32] = array("used"=>TRUE,"tag"=>"Disabled", "display"=>"Disabled", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
$dispfields["Match"][33] = array("used"=>TRUE,"tag"=>"Broken", "display"=>"Broken", "inputlen"=>3,"maxlen"=>3, "default_value"=>"");
//
// End of custom generated file
//
?>