<?php
//
// Competition System - Custom Parameters
//
// Generated: 2020-03-10 07:48:09
//


//
// Parameters for vargroup Bot
//
$dispfields["Bot"] = array();


//
// Parameters for vargroup Match
//
$dispfields["Match"] = array();


//
// Parameters for vargroup tBA
//
$ScoreFields = array();
$ScoreFields[0] = array("used"=>TRUE,"tag"=>"f_initLineRobot1", "tBAtag"=>"initLineRobot1", "display"=>"f_initLineRobot1" );
$ScoreFields[1] = array("used"=>TRUE,"tag"=>"f_endgameRobot1", "tBAtag"=>"endgameRobot1", "display"=>"f_endgameRobot1" );
$ScoreFields[2] = array("used"=>TRUE,"tag"=>"f_initLineRobot2", "tBAtag"=>"initLineRobot2", "display"=>"f_initLineRobot2" );
$ScoreFields[3] = array("used"=>TRUE,"tag"=>"f_endgameRobot2", "tBAtag"=>"endgameRobot2", "display"=>"f_endgameRobot2" );
$ScoreFields[4] = array("used"=>TRUE,"tag"=>"f_initLineRobot3", "tBAtag"=>"initLineRobot3", "display"=>"f_initLineRobot3" );
$ScoreFields[5] = array("used"=>TRUE,"tag"=>"f_endgameRobot3", "tBAtag"=>"endgameRobot3", "display"=>"f_endgameRobot3" );
$ScoreFields[6] = array("used"=>TRUE,"tag"=>"f_autoCellsBottom", "tBAtag"=>"autoCellsBottom", "display"=>"f_autoCellsBottom" );
$ScoreFields[7] = array("used"=>TRUE,"tag"=>"f_autoCellsOuter", "tBAtag"=>"autoCellsOuter", "display"=>"f_autoCellsOuter" );
$ScoreFields[8] = array("used"=>TRUE,"tag"=>"f_autoCellsInner", "tBAtag"=>"autoCellsInner", "display"=>"f_autoCellsInner" );
$ScoreFields[9] = array("used"=>TRUE,"tag"=>"f_teleopCellsBottom", "tBAtag"=>"teleopCellsBottom", "display"=>"f_teleopCellsBottom" );
$ScoreFields[10] = array("used"=>TRUE,"tag"=>"f_teleopCellsOuter", "tBAtag"=>"teleopCellsOuter", "display"=>"f_teleopCellsOuter" );
$ScoreFields[11] = array("used"=>TRUE,"tag"=>"f_teleopCellsInner", "tBAtag"=>"teleopCellsInner", "display"=>"f_teleopCellsInner" );
$ScoreFields[12] = array("used"=>TRUE,"tag"=>"f_stage1Activated", "tBAtag"=>"stage1Activated", "display"=>"f_stage1Activated" );
$ScoreFields[13] = array("used"=>TRUE,"tag"=>"f_stage2Activated", "tBAtag"=>"stage2Activated", "display"=>"f_stage2Activated" );
$ScoreFields[14] = array("used"=>TRUE,"tag"=>"f_stage3Activated", "tBAtag"=>"stage3Activated", "display"=>"f_stage3Activated" );
$ScoreFields[15] = array("used"=>TRUE,"tag"=>"f_stage3TargetColor", "tBAtag"=>"stage3TargetColor", "display"=>"f_stage3TargetColor" );
$ScoreFields[16] = array("used"=>TRUE,"tag"=>"f_endgameRungIsLevel", "tBAtag"=>"endgameRungIsLevel", "display"=>"f_endgameRungIsLevel" );
$ScoreFields[17] = array("used"=>TRUE,"tag"=>"f_autoInitLinePoints", "tBAtag"=>"autoInitLinePoints", "display"=>"f_autoInitLinePoints" );
$ScoreFields[18] = array("used"=>TRUE,"tag"=>"f_autoCellPoints", "tBAtag"=>"autoCellPoints", "display"=>"f_autoCellPoints" );
$ScoreFields[19] = array("used"=>TRUE,"tag"=>"f_autoPoints", "tBAtag"=>"autoPoints", "display"=>"f_autoPoints" );
$ScoreFields[20] = array("used"=>TRUE,"tag"=>"f_teleopCellPoints", "tBAtag"=>"teleopCellPoints", "display"=>"f_teleopCellPoints" );
$ScoreFields[21] = array("used"=>TRUE,"tag"=>"f_controlPanelPoints", "tBAtag"=>"controlPanelPoints", "display"=>"f_controlPanelPoints" );
$ScoreFields[22] = array("used"=>TRUE,"tag"=>"f_endgamePoints", "tBAtag"=>"endgamePoints", "display"=>"f_endgamePoints" );
$ScoreFields[23] = array("used"=>TRUE,"tag"=>"f_teleopPoints", "tBAtag"=>"teleopPoints", "display"=>"f_teleopPoints" );
$ScoreFields[24] = array("used"=>TRUE,"tag"=>"f_shieldOperationalR", "tBAtag"=>"shieldOperationalRankingPoint", "display"=>"f_shieldOperationalR" );
$ScoreFields[25] = array("used"=>TRUE,"tag"=>"f_shieldEnergizedRan", "tBAtag"=>"shieldEnergizedRankingPoint", "display"=>"f_shieldEnergizedRan" );
$ScoreFields[26] = array("used"=>TRUE,"tag"=>"f_tba_shieldEnergize", "tBAtag"=>"tba_shieldEnergizedRankingPointFromFoul", "display"=>"f_tba_shieldEnergize" );
$ScoreFields[27] = array("used"=>TRUE,"tag"=>"f_tba_numRobotsHangi", "tBAtag"=>"tba_numRobotsHanging", "display"=>"f_tba_numRobotsHangi" );
$ScoreFields[28] = array("used"=>TRUE,"tag"=>"f_foulCount", "tBAtag"=>"foulCount", "display"=>"f_foulCount" );
$ScoreFields[29] = array("used"=>TRUE,"tag"=>"f_techFoulCount", "tBAtag"=>"techFoulCount", "display"=>"f_techFoulCount" );
$ScoreFields[30] = array("used"=>TRUE,"tag"=>"f_adjustPoints", "tBAtag"=>"adjustPoints", "display"=>"f_adjustPoints" );
$ScoreFields[31] = array("used"=>TRUE,"tag"=>"f_foulPoints", "tBAtag"=>"foulPoints", "display"=>"f_foulPoints" );
$ScoreFields[32] = array("used"=>TRUE,"tag"=>"f_rp", "tBAtag"=>"rp", "display"=>"f_rp" );
$ScoreFields[33] = array("used"=>TRUE,"tag"=>"f_totalPoints", "tBAtag"=>"totalPoints", "display"=>"f_totalPoints" );


//
//
// tBA - Blue Alliance - custom fields score map
//   tBA score fields to custom score fields
$tba_score_to_match_alliance = array (
  "initLineRobot1"=>"f_initLineRobot1",
  "endgameRobot1"=>"f_endgameRobot1",
  "initLineRobot2"=>"f_initLineRobot2",
  "endgameRobot2"=>"f_endgameRobot2",
  "initLineRobot3"=>"f_initLineRobot3",
  "endgameRobot3"=>"f_endgameRobot3",
  "autoCellsBottom"=>"f_autoCellsBottom",
  "autoCellsOuter"=>"f_autoCellsOuter",
  "autoCellsInner"=>"f_autoCellsInner",
  "teleopCellsBottom"=>"f_teleopCellsBottom",
  "teleopCellsOuter"=>"f_teleopCellsOuter",
  "teleopCellsInner"=>"f_teleopCellsInner",
  "stage1Activated"=>"f_stage1Activated",
  "stage2Activated"=>"f_stage2Activated",
  "stage3Activated"=>"f_stage3Activated",
  "stage3TargetColor"=>"f_stage3TargetColor",
  "endgameRungIsLevel"=>"f_endgameRungIsLevel",
  "autoInitLinePoints"=>"f_autoInitLinePoints",
  "autoCellPoints"=>"f_autoCellPoints",
  "autoPoints"=>"f_autoPoints",
  "teleopCellPoints"=>"f_teleopCellPoints",
  "controlPanelPoints"=>"f_controlPanelPoints",
  "endgamePoints"=>"f_endgamePoints",
  "teleopPoints"=>"f_teleopPoints",
  "shieldOperationalRankingPoint"=>"f_shieldOperationalR",
  "shieldEnergizedRankingPoint"=>"f_shieldEnergizedRan",
  "tba_shieldEnergizedRankingPointFromFoul"=>"f_tba_shieldEnergize",
  "tba_numRobotsHanging"=>"f_tba_numRobotsHangi",
  "foulCount"=>"f_foulCount",
  "techFoulCount"=>"f_techFoulCount",
  "adjustPoints"=>"f_adjustPoints",
  "foulPoints"=>"f_foulPoints",
  "rp"=>"f_rp",
  "totalPoints"=>"f_totalPoints" );

//
// End of custom generated file
//
?>