#!/bin/bash
#
# $Revision: 1.3 $
# $Date: 2010/04/24 16:26:06 $
#
# Simple (hacked) script to create filedist systems from the fileshare system
#
# Desc: copies directories from $sourcehome to $disthome,
#   removes all RCS files/directories, then zips up each into a distribution
#   zip
#

#
# variables
#

# Directories in source home to copy and package.  Each directory becomes
#  a package
directories="CompetitionSystem"

# fileshare home
sourcehome=/home/www/robotics/files/fileshare

# filedist home
disthome=/home/www/robotics/files/filedist

######################################################################
#
# 

##
## special scripts
## 
echo "Running special scripts..."

# build interface def
grep '^/' $sourcehome/CompetitionSystem/htdocs/page.inc \
    > $sourcehome/CompetitionSystem/admin/doc/page-functions.txt


echo done.

##
## primary packaging section
##

echo "Beginning packing..."

for dir in $directories
do
  echo $dir...
  

  # remove and copy
  rm -rf $disthome/$dir
  cp -r $sourcehome/$dir $disthome/$dir

  # remove RCS files
  rm -rf $disthome/$dir/RCS
  rm -rf $disthome/$dir/*/RCS
  rm -rf $disthome/$dir/*/*/RCS
  rm -rf $disthome/$dir/*/*/*/RCS
  rm -rf $disthome/$dir/*/*/*/*/RCS
  rm -rf $disthome/$dir/*/*/*/*/*/RCS
  rm -rf $disthome/$dir/*/*/*/*/*/*/RCS
  rm -rf $disthome/$dir/*/*/*/*/*/*/*/RCS


  # package zip file
  cd $disthome/$dir

  # bump one version
  if [ -e ../$dir.zip.1 ]; then mv ../$dir.zip.1 ../$dir.zip.2; fi
  if [ -e ../$dir.zip ]; then mv ../$dir.zip ../$dir.zip.1; fi

  # rm -f ../$dir.zip
  zip -r ../$dir .

  echo "...done."
done
